### ISSUE TITLE
How to make use of the learned skills in the memory_library?

### ISSUE THREAD

**Issue by Raven-July** [cocacola-lab/MineLand#20]
I saw relevant code about saving memory_library in memory_library.py, but it seem that functions about loading a memory_library haven't been finished yet. So when the bot is doing similar tasks, it always choose to code new things rather than make use of previous code,which can sometimes lead to code error due to llm's fault.
I saw other projects such as "voyager" and a fork of "mindcraft" can save skills and load them.
So any suggestions on how to make use of the skill part in the memory_library?

**Comment by FooLiqi** [comment]
thx for your feedback, but since we wanna test Alex's social skill more, we did not implement the skill library.
