### ISSUE TITLE
Error comparing byte type and string in MineflayerManager listen_stdout and listen_stderr

### ISSUE THREAD

**Issue by jbarrerobuch** [cocacola-lab/MineLand#21]
```
def listen_stdout(self) :
        print('Start to listen stdout.')
        while True and self.process:
            output = self.process.stdout.readline()
            if output == '':
                continue
            if any(substr in output for substr in self.version_not_match_filter):
                print_error("Warning: Node.js version is not matched! Please use v18.18.2!")

            if 'started' in output:
                self.is_running = True
            print(output, end='')
        print("Mineflayer is end.")

def listen_stderr(self) :
        while True and self.process:
            output = self.process.stderr.readline()

            if output == '':
                continue
            if any(substr in output for substr in self.output_filter):
                continue
            if output.isspace():
                continue
            if any(substr in output for substr in self.version_not_match_filter):
                print_error("Warning: Node.js version is not matched! Please use v18.18.2!")

            print(output, end='')
```

The if statements in the while loop need to be nested to catch the different values of the output. And the condition:

`if any(substr in output for substr in self.version_not_match_filter)`

this returns an error because output is of type byte by definition (line 67 or line 81) and being compared to string.

`output = self.process.stdout.readline()`
`output = self.process.stderr.readline()`

I suggest as fix converting the value of output to string before comparing.

```
def listen_stdout(self) :
        print('Start to listen stdout.')
        while True and self.process:
            output = self.process.stdout.readline()
            output_str = output.decode('utf-8')

            if output == '':
                continue
            elif any(substr in output_str for substr in self.version_not_match_filter):
                print_error("Warning: Node.js version is not matched! Please use v18.18.2!")

            elif 'started' in output_str:
                self.is_running = True
            
            if output_str == '':
                print("...", end='\r')
            else:
                print(f"\n {output_str}")

        print("Mineflayer is end.")
    
    def listen_stderr(self) :
        while True and self.process:
            output = self.process.stderr.readline()
            output_str = output.decode('utf-8')

            if output == '':
                continue
            elif any(substr in output_str for substr in self.output_filter):
                continue
            elif output.isspace():
                continue
            elif any(substr in output_str for substr in self.version_not_match_filter):
                print_error("Warning: Node.js version is not matched! Please use v18.18.2!")

            if output_str == '':
                print("...", end='\r')
            else:
                print(output_str, end='')
```

also adding a conditional in the print statement in the end to avoid flooding the console.
However the value of output I get is always "" so there must be another issue somewhere.

**Comment by YXHXianYu** [comment]
Thank you for your feedback!

## Issue 1: The value of output
I just tested the code, and in my environment, the type is not an issue. `output = self.process.stdout.readline()` returns a `str`, not `bytes`. When creating the process, I added the parameter `text=True` , which typically makes `readline()` return a `str` directly without needing any conversion.

## Issue 2: if statement
Your suggestion makes sense. Using nested if statements would make the logic less prone to errors. I'll submit a PR with this fix shortly.

## Issue 3: Flooding the console
In my use case, I didn’t encounter this issue because I checked both `output == ''` and `output.isspace()`.

Considering the first issue, I suspect the difference might come from our environments. I tested this on both Windows 11 and Arch Linux with Python3.11. If possible, could you provide more detailed information about your environment?

Thank you again for your feedback!

**Comment by YXHXianYu** [comment]
Refer to #16 this issue, I found the differences.

I fixed these issues in the lastest PR.

Hope this helps you.

**Comment by jbarrerobuch** [comment]
Awesome! thanks!!

I have pulled the update but I got a java error. Not sure why is this happening my java version didn't change. i use openjdk 17 and NodeJs 18

```
Uncaught exception in thread "main"
java.lang.RuntimeException: An exception occurred when launching the server!
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:71)
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69)
Caused by: java.lang.RuntimeException: Error invoking MC server bundler: java.lang.UnsupportedClassVersionError: net/minecraft/bundler/Main has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at net.fabricmc.loader.impl.game.minecraft.BundlerProcessor.process(BundlerProcessor.java:102)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.locateGame(MinecraftGameProvider.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.createGameProvider(Knot.java:177)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:130)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23)
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69)
	... 1 more
Caused by: java.lang.UnsupportedClassVersionError: net/minecraft/bundler/Main has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at net.fabricmc.loader.impl.game.minecraft.BundlerProcessor$1.loadClass(BundlerProcessor.java:65)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at net.fabricmc.loader.impl.game.minecraft.BundlerProcessor.process(BundlerProcessor.java:85)
	... 7 more

```

**Comment by YXHXianYu** [comment]
This issue is most likely caused by a low java version. You can use `java -version` to check it.

If the above method doesn't solve the issue. You can modify the command in `server_manager.py` directly to check the environment(https://github.com/cocacola-lab/MineLand/blob/main/mineland/sim/server_manager.py#L92)

From:
```python
command = f"java -Xmx8G -jar fabric-server-mc.1.19-loader.0.14.18-launcher.0.11.2.jar nogui"
args = shlex.split(command)
```

To:
```python
command = f"java -version"
args = shlex.split(command)
```

This method will check the version that MineLand is actually using.

**Comment by jbarrerobuch** [comment]
ohh sorry I just deleted the comment.
I run it again and the exception didn't raise again, so I thought it could be because I did a new clone in a new folder and I forgot to install the java dependencies
`npm ci`

Thanks a lot for answering my doubts. I'm really interested in understanding you project, so If you don't mind I'll open some questions :)

**Comment by YXHXianYu** [comment]
> ohh sorry I just deleted the comment. I run it again and the exception didn't raise again, so I thought it could be because I did a new clone in a new folder and I forgot to install the java dependencies `npm ci`
> 
> Thanks a lot for answering my doubts. I'm really interested in understanding you project, so If you don't mind I'll open some questions :)

Thanks for your interest. Feel free to open any questions.

Just a heads-up: at the moment, our main focus isn't on MineLand. (though we might return to add new features in the future) So, for some complex issues, I might not respond immediately, but I'll do my best to get back to you as soon as possible. You can also submit PR directly (if you want), I'll review it.

**Comment by jbarrerobuch** [comment]
Awesome! I'm bit noob on this topic, i'll try my best.

Not sure why but it is getting freezed here. This is what happened before and I could fix it with the code above. running just the validate_install_simulator.py

![image](https://github.com/user-attachments/assets/3f3984cc-15cf-4d0d-a084-380eb0e667bf)

**Comment by YXHXianYu** [comment]
It seems to be caused by insufficient compute performance. MineLand requires at least 4G of memory. We suggest using MineLand in a home computer (or better).

I tested MineLand in a 4G Tencent Cloud server and it works properly.

**Comment by YXHXianYu** [comment]
MineLand needs to launch a Minecraft Server, so it needs some computing resource. 😢

**Comment by jbarrerobuch** [comment]
Ok I left it running and it took some time but it was completed.
It was simulating but the output was empty so nothing was printed in the console.

Thanks for your attention. :)
