### ISSUE TITLE
Analysing LLM/VLM behaviour and use of Gemini

### ISSUE THREAD

**Issue by jbarrerobuch** [cocacola-lab/MineLand#25]
Hi there team,

I had implemented the use of Gemini with multiple API keys to use the free tier from Google for training. I've implemented with Langchain so it works with the parsers etc.

I wanted test and male sure the prompt and the outputs are working fine and make sure that is not the reason why the bot is not making progress.

Any clue or experienced shared or your side on how did you test it is wellcome :)

kind regards,

Pepe
/

**Comment by FooLiqi** [comment]
please see issue #24
