### ISSUE TITLE
interface and open source model

### ISSUE THREAD

**Issue by WPH22** [cocacola-lab/MineLand#27]
**_'MineLand provides a set of Gym-style interfaces, similar to other simulators like MineDojo.'_**

Hello, I would like to ask, how can I use the interface? I did not find the detailed usage steps.

Also, I would like to ask, how can the simulator access an open source model? Is there a sample code?

**Comment by YXHXianYu** [comment]
> I would like to ask, how can I use the interface? I did not find the detailed usage steps.

Sry for that we dont have a detail documents. But we have some examples that show most of features.

In `./scripts` folder, we provide many example, including:
1. [observation_space.py](https://github.com/cocacola-lab/MineLand/blob/main/scripts/observation_space.py). It shows all of observation space. (If you don't familiar with gym-style api or observation space, you can refer to https://github.com/Farama-Foundation/Gymnasium or https://github.com/MineDojo/MineDojo)
2. [action_space_high_level.py](https://github.com/cocacola-lab/MineLand/blob/main/scripts/action_space_high_level.py). It shows how code controls the bots. In "High level action", you need to write **javascript code using mineflayer library**. You can refer to the following code and document: ① Default skill: [high_level_action](https://github.com/cocacola-lab/MineLand/tree/main/mineland/assets/high_level_action)；② Mineflayer API: [Mineflayer Docs](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md)
3. [action_space_low_level.py](https://github.com/cocacola-lab/MineLand/blob/main/scripts/action_space_low_level.py). It shows how to use **Low level action** (gym-style action space / Minedojo action space). You can refer to [MineDojo Docs - Action Space](https://docs.minedojo.org/sections/core_api/action_space.html)
4. [rgb_frame.py](https://github.com/cocacola-lab/MineLand/blob/main/scripts/rgb_frame.py). It shows how to access agent's first-personal view.
5. [rl_agent_expt.py](https://github.com/cocacola-lab/MineLand/blob/main/scripts/rl_agent_expt.py). It shows how to train RL Agent using MineLand (low-level action & observation) and stable_baselines3.
6. [connect_to_any_server.py](https://github.com/cocacola-lab/MineLand/blob/main/scripts/connect_to_any_server.py). It shows how to let agent access to an arbitrary server.

> how can the simulator access an open source model? Is there a sample code?

If you want to use RL model, you can refer to [rl_agent_expt.py](https://github.com/cocacola-lab/MineLand/blob/main/scripts/rl_agent_expt.py).

If you want to use LLM agent, you can refer to [alex_example.py](https://github.com/cocacola-lab/MineLand/blob/main/scripts/alex_example.py). It use Alex Agent we made. Alex code is in [This folder](https://github.com/cocacola-lab/MineLand/tree/main/mineland/alex)
