### ISSUE TITLE
llm and vlm

### ISSUE THREAD

**Issue by WPH22** [cocacola-lab/MineLand#31]
Hello,

I disabled all vlm in Alex's class and only enabled llm, but in the service area running log, I can still see the agent saying 'i see: xxxx'. I want to know how the agent obtains and identifies image information when only llm is used? Where is the relevant code?

Best,
WPH

**Comment by YXHXianYu** [comment]
Agent will receive information from observation space.

You can execute `scripts/observation_space.py` to see all information agents could get.

Tip: MineLand follow gym-style api, https://gymnasium.farama.org/index.html

**Comment by WPH22** [comment]
thanks！
