### ISSUE TITLE
How to use only LLM?

### ISSUE THREAD

**Issue by WPH22** [cocacola-lab/MineLand#32]
Hello,

In order to save tokens, I had to use only llm instead of vlm, so I changed all 'vision' in the global to False, and deleted all try: image_base64 = obs["rgb_base64"]... statements. In theory, gpt should not recognize the image.

But gpt still returns an explain that seems to have seen something. I would like to ask why? How can I make gpt completely give up recognizing images?
<img width="360" alt="image" src="https://github.com/user-attachments/assets/a6f3ed6f-3576-4be3-a27c-666b6013b698">

Best,
WPH

**Comment by YXHXianYu** [comment]
You may miss the prompts of action agent.

***

According to the picture your provided, the problem lies with the Action Agent (Action Module).

We also know, the output of an agent depends on the model and the prompts. Usually, the model is fixed, so the problem lies with the prompts.

So, lets review `mineland/alex/action/action_agent.py` to find something about the prompt of action agent.

In line 96-102:
```python
system_message = self.render_system_message()
human_message = self.render_human_message(obs, short_term_plan, code_info)

message = [system_message, human_message]

try:
    response = self.chain.invoke(message)
```
You can found that the prompt consists of system_message and human_message.

In function `def render_system_message`, you can found that the system prompt consists of `high_level_action_template.txt` and `high_level_action_response_format.txt`, which locates in directory `mineland/assets/prompt/`.

In `high_level_action_template.txt`, you can find the following content that must be modified to let gpt give up recognizing images:
```
RGB size: (height, weight)
RGB: ...
...
Explain (if applicable): What can you see in the RGB picture? 
...
    2) You can obtain the in-game information by looking at pictures. Observe the world with your eyes instead of using in-game information. Do not cheat. You must see the certain blocks in the RGB picture before use them as target. If you are not sure what you are looking at, you can use `bot.blockAtCursor(maxDistance=8)` or `bot.entityAtCursor(maxDistance=3.5)`.
...
    9) You must make sure there are targets in the RGB picture and use `bot.chat` to describe where is the target before use `bot.findBlocks` and `bot.findBlock`. Otherwise, it cannot be invoked. Do not cheat.
```

And in function `def render_human_message`, you can set image_base64 = "" to avoid appending image information into human message.

Remove these lines about `RGB`, I think action agent won't print anything about RGB picture.

***

In summary, you can try the following modification:

Firstly, change `high_level_action_template.txt` to 
```
You are a helpful assistant that writes Mineflayer javascript code to complete any Minecraft task specified by me.

Here are some useful programs written with Mineflayer APIs.

{programs}


At each round of conversation, I will give you

Code info: ...
Events: ...
Equipment: ...
Invenrtory: ...
Life states: ...
Location stats: ...
Task: ...
Plan: ...

You should then respond to me with
Explain (if applicable): Are there any steps missing in your plan? Why does the code not complete the task? What does code info imply? What can be inferred from these events? What impact do these events have on the task? How will you respond to these events?
Plan: How to complete the task step by step. You should pay attention to Inventory since it tells what you have.
Code:
    1) Write an async function taking the bot as the only argument.
    3) Reuse the above useful programs as much as possible.
        - Use `mineBlock(bot, name, count)` to collect blocks. Do not use `bot.dig` directly.
        - Use `craftItem(bot, name, count)` to craft items. Do not use `bot.craft` or `bot.recipesFor` directly.
        - Use `smeltItem(bot, name count)` to smelt items. Do not use `bot.openFurnace` directly.
        - Use `placeItem(bot, name, position)` to place blocks. Do not use `bot.placeBlock` directly.
        - Use `killMob(bot, name, timeout)` to kill mobs. Do not use `bot.attack` directly.
    4) Your function will be reused for building more complex functions. Therefore, you should make it generic and reusable. You should not make strong assumption about the inventory (as it may be changed at a later time), and therefore you should always check whether you have the required items before using them. If not, you should first collect the required items and reuse the above useful programs.
    5) Functions in the "Code from the last round" section will not be saved or executed. Do not reuse functions listed there.
    6) Anything defined outside a function will be ignored, define all your variables inside your functions.
    7) Call `bot.chat` to show the intermediate progress.
    8) You should select a direction at random every time instead of constantly using (1, 0, 1).
    10) `maxDistance` should always be 8 for `bot.findBlocks` and `bot.findBlock` and you must sure you can see it directly. Do not cheat.
    11) Do not write infinite loops or recursive functions.
    12) Do not use `bot.on` or `bot.once` to register event listeners. You definitely do not need them.
    13) Name your function in a meaningful way (can infer the task from the name).

You should only respond in the format as described below:
RESPONSE FORMAT:
{response_format}
```

Secondly, change `def render_human_message` to 
```python
    def render_human_message(self, obs, short_term_plan, code_info=None, critic_info=None):
        content = []
        text = ""
        text += f"short-term plan: {short_term_plan}\n"
        text += f"observation: {str(obs)}\n"
        if code_info is not None:
            text += f"code info: {code_info}\n"
        if critic_info is not None:
            text += f"critic info: {critic_info}\n"
        content.append({"type": "text", "text": text,})
        // remove these lines
        human_message = HumanMessage(content=content)
        return human_message
```

If you found that other agents have similar problems, you can solve them by modify prompts (system_message) and input (human_message).

Hope these help you.

**Comment by WPH22** [comment]
Thanks for your reply. I have tried to delete all the contents related to vision, rgb, image and picture in the template, including changing the content in programs.txt like 'To execute this command you must see xxx' to 'To execute this command xxx must exist', but the information printed by action agent still says 'i see....' or 'crafting table is also visible in rgb image'. What is going on?

**Comment by YXHXianYu** [comment]
> Thanks for your reply. I have tried to delete all the contents related to vision, rgb, image and picture in the template, including changing the content in programs.txt like 'To execute this command you must see xxx' to 'To execute this command xxx must exist', but the information printed by action agent still says 'i see....' or 'crafting table is also visible in rgb image'. What is going on?

It's strange. I have no idea what causes this. Maybe you can print `message` and further check it.

```python
message = [system_message, human_message]

// add this line
print(message)

try:
    response = self.chain.invoke(message)
```
