### ISSUE TITLE
In-game time flow speed

### ISSUE THREAD

**Issue by WPH22** [cocacola-lab/MineLand#33]
Hello,

I would like to adjust the in-game time flow speed. For example, I want to make the time pass at double the normal speed. Is there a built-in parameter or method in Mineland that allows for modifying the time scale, such as time_scale or similar? If not, could you suggest a recommended way to implement this, either by tweaking the environment settings or by manipulating the simulation steps?

Thank you in advance for your help!

**Comment by YXHXianYu** [comment]
MineLand has no method to implement "make the time pass at double the normal speed".

MineLand provides a parameter "ticks_per_step", which only affects the time taken by `mland.tick()` and cannot modify the time scale. MineLand also provides a parameter `enable_auto_pause`, but this function isn't stable and we don't recommend to use it.

BTW, Minecraft doesn't support this function. To implement this, we must develop a mod using Fabric or Forge. It's a bit difficult.

**Comment by WPH22** [comment]
Thanks for your reply！
