### ISSUE TITLE
Error on tech tree mission

### ISSUE THREAD

**Issue by WPH22** [cocacola-lab/MineLand#38]
![image](https://github.com/user-attachments/assets/eeb9c90d-0111-4720-8ca0-485ea0b5da17)

Hello,
I'm trying to have two Alex Agents complete a tech tree mission, but every time they fail after a while, they report an error and the agents are disconnected. What's the reason?

**Comment by YXHXianYu** [comment]
It seems an error from mineflayer (javascript side). I have no experience dealing with this error.

According to `JavaScript heap out of memory`, you can increase the amount of heap memory that javascript can use. https://stackoverflow.com/questions/38558989/node-js-heap-out-of-memory

**Comment by WPH22** [comment]
thanks！
