### ISSUE TITLE
limitations on the sensor perception of players

### ISSUE THREAD

**Issue by WPH22** [cocacola-lab/MineLand#39]
Hello,

From the paper, I noticed the following two paragraphs.

1.
“We refer to the mechanisms of human vision and hearing, and impose limitations on the sensor perception of players, including distance attenuation, environmental obstructions, and directional constraints, to model the limited senses.”
2.
“Importantly, to approach the real world, we’ve added a restriction on multimodal information, where Alex can obtain the location of the target only when it can visually discover or reason about the target’s presence nearby. This is because our agent Alex has the feature of limited senses. However, Voyager can ‘cheat’. Voyager obtains the location of the target directly from the system even though they have not seen the target.”

How did you implement these limitations? I want to know how to cancel the limitations on the sensor perception of players, because I want to control the agent only through LLM instead of multimodal, and too weak perception cannot enable the agent to complete the task.

Could you give me some advice or tips?

Thanks!

**Comment by YXHXianYu** [comment]
We use prompt to implement most of limitations. There are some `Do not cheat` in https://github.com/cocacola-lab/MineLand/blob/main/mineland/assets/prompt/high_level_action_template.txt.

For distance attenuation, we implement it in javascript side. You can check all `this.hearing_distance` in https://github.com/cocacola-lab/MineLand/blob/main/mineland/sim/mineflayer/bot_manager.js to see this kind of limitations.

**Comment by WPH22** [comment]
thanks！
